### ISSUE TITLE
Missing: CHANGELOG, tags

### ISSUE THREAD

**Issue by andreasabel** [hanshoglund/monadplus#11]
This project lacks a changelog.  It would be helpful to have one when investigating issues, like #8.

Also, it would be good to have the released versions tagged in this repo.  This way, one can easily get a precise aggregation of the changes between the releases.

**Comment by ocharles** [comment]
I agree. I'll sort both of those out

**Comment by ocharles** [comment]
`CHANGELOG.md` added, along with tags. This was a bit of a software archaeology project, so I've done the best I can!

**Comment by andreasabel** [comment]
Excellent, thanks! https://github.com/hanshoglund/monadplus/blob/25b49eb6412bacb019aaa117a6b77e00ad7b3417/CHANGELOG.md
