### ISSUE TITLE
Package monadplus does not build under ghc 8.6

### ISSUE THREAD

**Issue by andreasabel** [hanshoglund/monadplus#4]
Package monadplus does not build under ghc 8.6.
Is this package still actively maintained?

**Comment by OndrejPopp** [comment]
Have a look at the "Added Semigroup instance" pull request. I applied a similar fix to my local copy.

**Comment by ocharles** [comment]
GHC 8.6 is very old now, and I think outside the support window for this library. I'm going to close this now.
