### ISSUE TITLE
Does this repo contain the changes for 1.4.3?

### ISSUE THREAD

**Issue by andreasabel** [hanshoglund/monadplus#9]
The repo has 1.4.2:
https://github.com/hanshoglund/monadplus/blob/7f1bfd12f66c33db503c6ff0b4f6965681d95c8d/monadplus.cabal#L2-L3

However, hackage has 1.4.3 and points to this repository.

Ollie @ocharles, where are the latest sources hosted if not here?  
(Or maybe you didn't merge the changes in here yet.  In this case, please do so, so that you can receive contributions.)
(Or is just the version bump not committed yet?)

**Comment by ocharles** [comment]
Strange, I must have missed a push. I'll push later today

**Comment by ocharles** [comment]
https://github.com/hanshoglund/monadplus/commit/a091862c8f11d3d0b1a4779834aeb3d81c5b10e0 pushed, along with tag (https://github.com/hanshoglund/monadplus/releases/tag/1.4.3).
